// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpyukUrqM0Ia2SQgJeNAe7uUDCrqldhbY',
    appId: '1:655087923624:web:29f81622f510fe0fcbed9d',
    messagingSenderId: '655087923624',
    projectId: 'lapcare-338db',
    authDomain: 'lapcare-338db.firebaseapp.com',
    storageBucket: 'lapcare-338db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgLY-ho0Vg2Xlt1qLOIGDkEYs_JTj9VQ',
    appId: '1:655087923624:android:312adc87ccd51580cbed9d',
    messagingSenderId: '655087923624',
    projectId: 'lapcare-338db',
    storageBucket: 'lapcare-338db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIaA7F2ToJ-xLVhUwaDjlU4cmbjtRDQ9o',
    appId: '1:655087923624:ios:a251e100ea19ac6ecbed9d',
    messagingSenderId: '655087923624',
    projectId: 'lapcare-338db',
    storageBucket: 'lapcare-338db.appspot.com',
    iosClientId: '655087923624-5e2i5rqtnovlqin5aql9r0471cr3dfe6.apps.googleusercontent.com',
    iosBundleId: 'com.example.lapcare',
  );
}
